# Generated by Django 6.0.3 on 2026-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("preview", models.CharField(max_length=200)),
                ("conent", models.TextField()),
                ("date", models.DateField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("image", models.CharField(max_length=50)),
            ],
        ),
    ]
