# Generated by Django 6.0.3 on 2026-04-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_author_tag_rename_conent_post_content_post_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="lat_name",
            new_name="last_name",
        ),
    ]
